version: "3"

networks:
  webapp:

services:
  app:
    build: ./
    container_name: ${APP_NAME}_app
    ports:
      - "8090:80"
    volumes:
      - ./:/app
    networks:
      - webapp

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: ${APP_NAME}_mongo
    volumes:
      - ./docker/mongo:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - webapp

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - webapp
    depends_on:
      - mongo
    container_name: ${APP_NAME}_mongo_express
